// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func saveFieldData() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_saveFieldData_0034`,
		Function: `function __templ_saveFieldData_0034(){var fields = [
		"username", "password", "password_confirm", "first_name", "last_name", "email", "phonenumber",
	
	];
	htmx.onLoad(function(elt) {
		var classToListen = "form-submit-btn";
		var classBtn = document.getElementsByClassName(classToListen)[0];

		if (classBtn !== undefined || classBtn !== null) {
			fields.flatMap((x) => {
				var field = document.getElementById(x);
				if (field) {
					var fieldVal = sessionStorage.getItem(x);
					if (fieldVal) {
						field.value = fieldVal
					};
				}

			})

			if (classBtn) {
			htmx.on(classBtn, "click", function(evt) {
				fields.flatMap((x) => {
					var field = document.getElementById(x);
					if (field) {
						sessionStorage.setItem(x, field.value);
					}
				})
			});
		}
	}})}`,
		Call:       templ.SafeScript(`__templ_saveFieldData_0034`),
		CallInline: templ.SafeScriptInline(`__templ_saveFieldData_0034`),
	}
}

func FieldDataSaver() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = saveFieldData().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
