// Code generated by ent, DO NOT EDIT.

package attributevariantnum

import (
	"prodcat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldLTE(FieldID, id))
}

// AttributeID applies equality check predicate on the "attribute_id" field. It's identical to AttributeIDEQ.
func AttributeID(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldEQ(FieldAttributeID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldEQ(FieldValue, v))
}

// AttributeIDEQ applies the EQ predicate on the "attribute_id" field.
func AttributeIDEQ(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldEQ(FieldAttributeID, v))
}

// AttributeIDNEQ applies the NEQ predicate on the "attribute_id" field.
func AttributeIDNEQ(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldNEQ(FieldAttributeID, v))
}

// AttributeIDIn applies the In predicate on the "attribute_id" field.
func AttributeIDIn(vs ...int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldIn(FieldAttributeID, vs...))
}

// AttributeIDNotIn applies the NotIn predicate on the "attribute_id" field.
func AttributeIDNotIn(vs ...int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldNotIn(FieldAttributeID, vs...))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v int) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.FieldLTE(FieldValue, v))
}

// HasAttribute applies the HasEdge predicate on the "attribute" edge.
func HasAttribute() predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AttributeTable, AttributeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttributeWith applies the HasEdge predicate on the "attribute" edge with a given conditions (other predicates).
func HasAttributeWith(preds ...predicate.Attribute) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(func(s *sql.Selector) {
		step := newAttributeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AttributeVariantNum) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AttributeVariantNum) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AttributeVariantNum) predicate.AttributeVariantNum {
	return predicate.AttributeVariantNum(sql.NotPredicates(p))
}
