// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"prodcat/ent/attributevaluenum"
	"prodcat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttributeValueNumDelete is the builder for deleting a AttributeValueNum entity.
type AttributeValueNumDelete struct {
	config
	hooks    []Hook
	mutation *AttributeValueNumMutation
}

// Where appends a list predicates to the AttributeValueNumDelete builder.
func (avnd *AttributeValueNumDelete) Where(ps ...predicate.AttributeValueNum) *AttributeValueNumDelete {
	avnd.mutation.Where(ps...)
	return avnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (avnd *AttributeValueNumDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, avnd.sqlExec, avnd.mutation, avnd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (avnd *AttributeValueNumDelete) ExecX(ctx context.Context) int {
	n, err := avnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (avnd *AttributeValueNumDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(attributevaluenum.Table, sqlgraph.NewFieldSpec(attributevaluenum.FieldID, field.TypeInt))
	if ps := avnd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, avnd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	avnd.mutation.done = true
	return affected, err
}

// AttributeValueNumDeleteOne is the builder for deleting a single AttributeValueNum entity.
type AttributeValueNumDeleteOne struct {
	avnd *AttributeValueNumDelete
}

// Where appends a list predicates to the AttributeValueNumDelete builder.
func (avndo *AttributeValueNumDeleteOne) Where(ps ...predicate.AttributeValueNum) *AttributeValueNumDeleteOne {
	avndo.avnd.mutation.Where(ps...)
	return avndo
}

// Exec executes the deletion query.
func (avndo *AttributeValueNumDeleteOne) Exec(ctx context.Context) error {
	n, err := avndo.avnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attributevaluenum.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (avndo *AttributeValueNumDeleteOne) ExecX(ctx context.Context) {
	if err := avndo.Exec(ctx); err != nil {
		panic(err)
	}
}
