// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"prodcat/ent/attributevaluestring"
	"prodcat/ent/attributevariantstring"
	"prodcat/ent/product"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AttributeValueString is the model entity for the AttributeValueString schema.
type AttributeValueString struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// VariantID holds the value of the "variant_id" field.
	VariantID int `json:"variant_id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int `json:"product_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttributeValueStringQuery when eager-loading is set.
	Edges        AttributeValueStringEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AttributeValueStringEdges holds the relations/edges for other nodes in the graph.
type AttributeValueStringEdges struct {
	// Variant holds the value of the variant edge.
	Variant *AttributeVariantString `json:"variant,omitempty"`
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// VariantOrErr returns the Variant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttributeValueStringEdges) VariantOrErr() (*AttributeVariantString, error) {
	if e.loadedTypes[0] {
		if e.Variant == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: attributevariantstring.Label}
		}
		return e.Variant, nil
	}
	return nil, &NotLoadedError{edge: "variant"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttributeValueStringEdges) ProductOrErr() (*Product, error) {
	if e.loadedTypes[1] {
		if e.Product == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: product.Label}
		}
		return e.Product, nil
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AttributeValueString) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attributevaluestring.FieldID, attributevaluestring.FieldVariantID, attributevaluestring.FieldProductID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AttributeValueString fields.
func (avs *AttributeValueString) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attributevaluestring.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			avs.ID = int(value.Int64)
		case attributevaluestring.FieldVariantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field variant_id", values[i])
			} else if value.Valid {
				avs.VariantID = int(value.Int64)
			}
		case attributevaluestring.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				avs.ProductID = int(value.Int64)
			}
		default:
			avs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AttributeValueString.
// This includes values selected through modifiers, order, etc.
func (avs *AttributeValueString) Value(name string) (ent.Value, error) {
	return avs.selectValues.Get(name)
}

// QueryVariant queries the "variant" edge of the AttributeValueString entity.
func (avs *AttributeValueString) QueryVariant() *AttributeVariantStringQuery {
	return NewAttributeValueStringClient(avs.config).QueryVariant(avs)
}

// QueryProduct queries the "product" edge of the AttributeValueString entity.
func (avs *AttributeValueString) QueryProduct() *ProductQuery {
	return NewAttributeValueStringClient(avs.config).QueryProduct(avs)
}

// Update returns a builder for updating this AttributeValueString.
// Note that you need to call AttributeValueString.Unwrap() before calling this method if this AttributeValueString
// was returned from a transaction, and the transaction was committed or rolled back.
func (avs *AttributeValueString) Update() *AttributeValueStringUpdateOne {
	return NewAttributeValueStringClient(avs.config).UpdateOne(avs)
}

// Unwrap unwraps the AttributeValueString entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (avs *AttributeValueString) Unwrap() *AttributeValueString {
	_tx, ok := avs.config.driver.(*txDriver)
	if !ok {
		panic("ent: AttributeValueString is not a transactional entity")
	}
	avs.config.driver = _tx.drv
	return avs
}

// String implements the fmt.Stringer.
func (avs *AttributeValueString) String() string {
	var builder strings.Builder
	builder.WriteString("AttributeValueString(")
	builder.WriteString(fmt.Sprintf("id=%v, ", avs.ID))
	builder.WriteString("variant_id=")
	builder.WriteString(fmt.Sprintf("%v", avs.VariantID))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", avs.ProductID))
	builder.WriteByte(')')
	return builder.String()
}

// AttributeValueStrings is a parsable slice of AttributeValueString.
type AttributeValueStrings []*AttributeValueString
