// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"prodcat/ent/attribute"
	"prodcat/ent/attributevariantnum"
	"prodcat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttributeVariantNumQuery is the builder for querying AttributeVariantNum entities.
type AttributeVariantNumQuery struct {
	config
	ctx           *QueryContext
	order         []attributevariantnum.OrderOption
	inters        []Interceptor
	predicates    []predicate.AttributeVariantNum
	withAttribute *AttributeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AttributeVariantNumQuery builder.
func (avnq *AttributeVariantNumQuery) Where(ps ...predicate.AttributeVariantNum) *AttributeVariantNumQuery {
	avnq.predicates = append(avnq.predicates, ps...)
	return avnq
}

// Limit the number of records to be returned by this query.
func (avnq *AttributeVariantNumQuery) Limit(limit int) *AttributeVariantNumQuery {
	avnq.ctx.Limit = &limit
	return avnq
}

// Offset to start from.
func (avnq *AttributeVariantNumQuery) Offset(offset int) *AttributeVariantNumQuery {
	avnq.ctx.Offset = &offset
	return avnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (avnq *AttributeVariantNumQuery) Unique(unique bool) *AttributeVariantNumQuery {
	avnq.ctx.Unique = &unique
	return avnq
}

// Order specifies how the records should be ordered.
func (avnq *AttributeVariantNumQuery) Order(o ...attributevariantnum.OrderOption) *AttributeVariantNumQuery {
	avnq.order = append(avnq.order, o...)
	return avnq
}

// QueryAttribute chains the current query on the "attribute" edge.
func (avnq *AttributeVariantNumQuery) QueryAttribute() *AttributeQuery {
	query := (&AttributeClient{config: avnq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := avnq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := avnq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attributevariantnum.Table, attributevariantnum.FieldID, selector),
			sqlgraph.To(attribute.Table, attribute.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attributevariantnum.AttributeTable, attributevariantnum.AttributeColumn),
		)
		fromU = sqlgraph.SetNeighbors(avnq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AttributeVariantNum entity from the query.
// Returns a *NotFoundError when no AttributeVariantNum was found.
func (avnq *AttributeVariantNumQuery) First(ctx context.Context) (*AttributeVariantNum, error) {
	nodes, err := avnq.Limit(1).All(setContextOp(ctx, avnq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{attributevariantnum.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (avnq *AttributeVariantNumQuery) FirstX(ctx context.Context) *AttributeVariantNum {
	node, err := avnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AttributeVariantNum ID from the query.
// Returns a *NotFoundError when no AttributeVariantNum ID was found.
func (avnq *AttributeVariantNumQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = avnq.Limit(1).IDs(setContextOp(ctx, avnq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{attributevariantnum.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (avnq *AttributeVariantNumQuery) FirstIDX(ctx context.Context) int {
	id, err := avnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AttributeVariantNum entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AttributeVariantNum entity is found.
// Returns a *NotFoundError when no AttributeVariantNum entities are found.
func (avnq *AttributeVariantNumQuery) Only(ctx context.Context) (*AttributeVariantNum, error) {
	nodes, err := avnq.Limit(2).All(setContextOp(ctx, avnq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{attributevariantnum.Label}
	default:
		return nil, &NotSingularError{attributevariantnum.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (avnq *AttributeVariantNumQuery) OnlyX(ctx context.Context) *AttributeVariantNum {
	node, err := avnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AttributeVariantNum ID in the query.
// Returns a *NotSingularError when more than one AttributeVariantNum ID is found.
// Returns a *NotFoundError when no entities are found.
func (avnq *AttributeVariantNumQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = avnq.Limit(2).IDs(setContextOp(ctx, avnq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{attributevariantnum.Label}
	default:
		err = &NotSingularError{attributevariantnum.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (avnq *AttributeVariantNumQuery) OnlyIDX(ctx context.Context) int {
	id, err := avnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AttributeVariantNums.
func (avnq *AttributeVariantNumQuery) All(ctx context.Context) ([]*AttributeVariantNum, error) {
	ctx = setContextOp(ctx, avnq.ctx, "All")
	if err := avnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AttributeVariantNum, *AttributeVariantNumQuery]()
	return withInterceptors[[]*AttributeVariantNum](ctx, avnq, qr, avnq.inters)
}

// AllX is like All, but panics if an error occurs.
func (avnq *AttributeVariantNumQuery) AllX(ctx context.Context) []*AttributeVariantNum {
	nodes, err := avnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AttributeVariantNum IDs.
func (avnq *AttributeVariantNumQuery) IDs(ctx context.Context) (ids []int, err error) {
	if avnq.ctx.Unique == nil && avnq.path != nil {
		avnq.Unique(true)
	}
	ctx = setContextOp(ctx, avnq.ctx, "IDs")
	if err = avnq.Select(attributevariantnum.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (avnq *AttributeVariantNumQuery) IDsX(ctx context.Context) []int {
	ids, err := avnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (avnq *AttributeVariantNumQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, avnq.ctx, "Count")
	if err := avnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, avnq, querierCount[*AttributeVariantNumQuery](), avnq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (avnq *AttributeVariantNumQuery) CountX(ctx context.Context) int {
	count, err := avnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (avnq *AttributeVariantNumQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, avnq.ctx, "Exist")
	switch _, err := avnq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (avnq *AttributeVariantNumQuery) ExistX(ctx context.Context) bool {
	exist, err := avnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AttributeVariantNumQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (avnq *AttributeVariantNumQuery) Clone() *AttributeVariantNumQuery {
	if avnq == nil {
		return nil
	}
	return &AttributeVariantNumQuery{
		config:        avnq.config,
		ctx:           avnq.ctx.Clone(),
		order:         append([]attributevariantnum.OrderOption{}, avnq.order...),
		inters:        append([]Interceptor{}, avnq.inters...),
		predicates:    append([]predicate.AttributeVariantNum{}, avnq.predicates...),
		withAttribute: avnq.withAttribute.Clone(),
		// clone intermediate query.
		sql:  avnq.sql.Clone(),
		path: avnq.path,
	}
}

// WithAttribute tells the query-builder to eager-load the nodes that are connected to
// the "attribute" edge. The optional arguments are used to configure the query builder of the edge.
func (avnq *AttributeVariantNumQuery) WithAttribute(opts ...func(*AttributeQuery)) *AttributeVariantNumQuery {
	query := (&AttributeClient{config: avnq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	avnq.withAttribute = query
	return avnq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AttributeID int `json:"attribute_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AttributeVariantNum.Query().
//		GroupBy(attributevariantnum.FieldAttributeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (avnq *AttributeVariantNumQuery) GroupBy(field string, fields ...string) *AttributeVariantNumGroupBy {
	avnq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AttributeVariantNumGroupBy{build: avnq}
	grbuild.flds = &avnq.ctx.Fields
	grbuild.label = attributevariantnum.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AttributeID int `json:"attribute_id,omitempty"`
//	}
//
//	client.AttributeVariantNum.Query().
//		Select(attributevariantnum.FieldAttributeID).
//		Scan(ctx, &v)
func (avnq *AttributeVariantNumQuery) Select(fields ...string) *AttributeVariantNumSelect {
	avnq.ctx.Fields = append(avnq.ctx.Fields, fields...)
	sbuild := &AttributeVariantNumSelect{AttributeVariantNumQuery: avnq}
	sbuild.label = attributevariantnum.Label
	sbuild.flds, sbuild.scan = &avnq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AttributeVariantNumSelect configured with the given aggregations.
func (avnq *AttributeVariantNumQuery) Aggregate(fns ...AggregateFunc) *AttributeVariantNumSelect {
	return avnq.Select().Aggregate(fns...)
}

func (avnq *AttributeVariantNumQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range avnq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, avnq); err != nil {
				return err
			}
		}
	}
	for _, f := range avnq.ctx.Fields {
		if !attributevariantnum.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if avnq.path != nil {
		prev, err := avnq.path(ctx)
		if err != nil {
			return err
		}
		avnq.sql = prev
	}
	return nil
}

func (avnq *AttributeVariantNumQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AttributeVariantNum, error) {
	var (
		nodes       = []*AttributeVariantNum{}
		_spec       = avnq.querySpec()
		loadedTypes = [1]bool{
			avnq.withAttribute != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AttributeVariantNum).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AttributeVariantNum{config: avnq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, avnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := avnq.withAttribute; query != nil {
		if err := avnq.loadAttribute(ctx, query, nodes, nil,
			func(n *AttributeVariantNum, e *Attribute) { n.Edges.Attribute = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (avnq *AttributeVariantNumQuery) loadAttribute(ctx context.Context, query *AttributeQuery, nodes []*AttributeVariantNum, init func(*AttributeVariantNum), assign func(*AttributeVariantNum, *Attribute)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AttributeVariantNum)
	for i := range nodes {
		fk := nodes[i].AttributeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(attribute.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "attribute_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (avnq *AttributeVariantNumQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := avnq.querySpec()
	_spec.Node.Columns = avnq.ctx.Fields
	if len(avnq.ctx.Fields) > 0 {
		_spec.Unique = avnq.ctx.Unique != nil && *avnq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, avnq.driver, _spec)
}

func (avnq *AttributeVariantNumQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(attributevariantnum.Table, attributevariantnum.Columns, sqlgraph.NewFieldSpec(attributevariantnum.FieldID, field.TypeInt))
	_spec.From = avnq.sql
	if unique := avnq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if avnq.path != nil {
		_spec.Unique = true
	}
	if fields := avnq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attributevariantnum.FieldID)
		for i := range fields {
			if fields[i] != attributevariantnum.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if avnq.withAttribute != nil {
			_spec.Node.AddColumnOnce(attributevariantnum.FieldAttributeID)
		}
	}
	if ps := avnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := avnq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := avnq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := avnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (avnq *AttributeVariantNumQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(avnq.driver.Dialect())
	t1 := builder.Table(attributevariantnum.Table)
	columns := avnq.ctx.Fields
	if len(columns) == 0 {
		columns = attributevariantnum.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if avnq.sql != nil {
		selector = avnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if avnq.ctx.Unique != nil && *avnq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range avnq.predicates {
		p(selector)
	}
	for _, p := range avnq.order {
		p(selector)
	}
	if offset := avnq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := avnq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AttributeVariantNumGroupBy is the group-by builder for AttributeVariantNum entities.
type AttributeVariantNumGroupBy struct {
	selector
	build *AttributeVariantNumQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (avngb *AttributeVariantNumGroupBy) Aggregate(fns ...AggregateFunc) *AttributeVariantNumGroupBy {
	avngb.fns = append(avngb.fns, fns...)
	return avngb
}

// Scan applies the selector query and scans the result into the given value.
func (avngb *AttributeVariantNumGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, avngb.build.ctx, "GroupBy")
	if err := avngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttributeVariantNumQuery, *AttributeVariantNumGroupBy](ctx, avngb.build, avngb, avngb.build.inters, v)
}

func (avngb *AttributeVariantNumGroupBy) sqlScan(ctx context.Context, root *AttributeVariantNumQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(avngb.fns))
	for _, fn := range avngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*avngb.flds)+len(avngb.fns))
		for _, f := range *avngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*avngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := avngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AttributeVariantNumSelect is the builder for selecting fields of AttributeVariantNum entities.
type AttributeVariantNumSelect struct {
	*AttributeVariantNumQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (avns *AttributeVariantNumSelect) Aggregate(fns ...AggregateFunc) *AttributeVariantNumSelect {
	avns.fns = append(avns.fns, fns...)
	return avns
}

// Scan applies the selector query and scans the result into the given value.
func (avns *AttributeVariantNumSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, avns.ctx, "Select")
	if err := avns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttributeVariantNumQuery, *AttributeVariantNumSelect](ctx, avns.AttributeVariantNumQuery, avns, avns.inters, v)
}

func (avns *AttributeVariantNumSelect) sqlScan(ctx context.Context, root *AttributeVariantNumQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(avns.fns))
	for _, fn := range avns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*avns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := avns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
