// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"prodcat/ent/attributevariantstring"
	"prodcat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttributeVariantStringDelete is the builder for deleting a AttributeVariantString entity.
type AttributeVariantStringDelete struct {
	config
	hooks    []Hook
	mutation *AttributeVariantStringMutation
}

// Where appends a list predicates to the AttributeVariantStringDelete builder.
func (avsd *AttributeVariantStringDelete) Where(ps ...predicate.AttributeVariantString) *AttributeVariantStringDelete {
	avsd.mutation.Where(ps...)
	return avsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (avsd *AttributeVariantStringDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, avsd.sqlExec, avsd.mutation, avsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (avsd *AttributeVariantStringDelete) ExecX(ctx context.Context) int {
	n, err := avsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (avsd *AttributeVariantStringDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(attributevariantstring.Table, sqlgraph.NewFieldSpec(attributevariantstring.FieldID, field.TypeInt))
	if ps := avsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, avsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	avsd.mutation.done = true
	return affected, err
}

// AttributeVariantStringDeleteOne is the builder for deleting a single AttributeVariantString entity.
type AttributeVariantStringDeleteOne struct {
	avsd *AttributeVariantStringDelete
}

// Where appends a list predicates to the AttributeVariantStringDelete builder.
func (avsdo *AttributeVariantStringDeleteOne) Where(ps ...predicate.AttributeVariantString) *AttributeVariantStringDeleteOne {
	avsdo.avsd.mutation.Where(ps...)
	return avsdo
}

// Exec executes the deletion query.
func (avsdo *AttributeVariantStringDeleteOne) Exec(ctx context.Context) error {
	n, err := avsdo.avsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attributevariantstring.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (avsdo *AttributeVariantStringDeleteOne) ExecX(ctx context.Context) {
	if err := avsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
