// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"prodcat/ent/schema"
	"prodcat/ent/usersettings"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSettingsCreate is the builder for creating a UserSettings entity.
type UserSettingsCreate struct {
	config
	mutation *UserSettingsMutation
	hooks    []Hook
}

// SetFrontend sets the "frontend" field.
func (usc *UserSettingsCreate) SetFrontend(ss schema.DefaultSetting) *UserSettingsCreate {
	usc.mutation.SetFrontend(ss)
	return usc
}

// SetNillableFrontend sets the "frontend" field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableFrontend(ss *schema.DefaultSetting) *UserSettingsCreate {
	if ss != nil {
		usc.SetFrontend(*ss)
	}
	return usc
}

// Mutation returns the UserSettingsMutation object of the builder.
func (usc *UserSettingsCreate) Mutation() *UserSettingsMutation {
	return usc.mutation
}

// Save creates the UserSettings in the database.
func (usc *UserSettingsCreate) Save(ctx context.Context) (*UserSettings, error) {
	usc.defaults()
	return withHooks(ctx, usc.sqlSave, usc.mutation, usc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (usc *UserSettingsCreate) SaveX(ctx context.Context) *UserSettings {
	v, err := usc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (usc *UserSettingsCreate) Exec(ctx context.Context) error {
	_, err := usc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usc *UserSettingsCreate) ExecX(ctx context.Context) {
	if err := usc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usc *UserSettingsCreate) defaults() {
	if _, ok := usc.mutation.Frontend(); !ok {
		v := usersettings.DefaultFrontend
		usc.mutation.SetFrontend(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usc *UserSettingsCreate) check() error {
	if _, ok := usc.mutation.Frontend(); !ok {
		return &ValidationError{Name: "frontend", err: errors.New(`ent: missing required field "UserSettings.frontend"`)}
	}
	return nil
}

func (usc *UserSettingsCreate) sqlSave(ctx context.Context) (*UserSettings, error) {
	if err := usc.check(); err != nil {
		return nil, err
	}
	_node, _spec := usc.createSpec()
	if err := sqlgraph.CreateNode(ctx, usc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	usc.mutation.id = &_node.ID
	usc.mutation.done = true
	return _node, nil
}

func (usc *UserSettingsCreate) createSpec() (*UserSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSettings{config: usc.config}
		_spec = sqlgraph.NewCreateSpec(usersettings.Table, sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt))
	)
	if value, ok := usc.mutation.Frontend(); ok {
		_spec.SetField(usersettings.FieldFrontend, field.TypeJSON, value)
		_node.Frontend = value
	}
	return _node, _spec
}

// UserSettingsCreateBulk is the builder for creating many UserSettings entities in bulk.
type UserSettingsCreateBulk struct {
	config
	err      error
	builders []*UserSettingsCreate
}

// Save creates the UserSettings entities in the database.
func (uscb *UserSettingsCreateBulk) Save(ctx context.Context) ([]*UserSettings, error) {
	if uscb.err != nil {
		return nil, uscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uscb.builders))
	nodes := make([]*UserSettings, len(uscb.builders))
	mutators := make([]Mutator, len(uscb.builders))
	for i := range uscb.builders {
		func(i int, root context.Context) {
			builder := uscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uscb *UserSettingsCreateBulk) SaveX(ctx context.Context) []*UserSettings {
	v, err := uscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uscb *UserSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := uscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uscb *UserSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := uscb.Exec(ctx); err != nil {
		panic(err)
	}
}
