-- Create "attributes" table
CREATE TABLE "attributes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "sort_order" bigint NOT NULL, "is_required" boolean NULL, PRIMARY KEY ("id"));
-- Create "products" table
CREATE TABLE "products" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "attribute_values" table
CREATE TABLE "attribute_values" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "type" character varying NOT NULL, "value" character varying NOT NULL, "attribute_attribute_values" bigint NOT NULL, "product_attribute_values" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "attribute_values_attributes_attributeValues" FOREIGN KEY ("attribute_attribute_values") REFERENCES "attributes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "attribute_values_products_attributeValues" FOREIGN KEY ("product_attribute_values") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
